# Generated by Django 5.0.4 on 2024-04-16 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_bank_account_alter_user_card_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
