# Generated by Django 5.0.4 on 2024-04-16 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_data_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 4, 16, 58, 447269, tzinfo=datetime.timezone.utc)),
        ),
    ]
