# Generated by Django 5.0.4 on 2024-04-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin_code',
        ),
    ]
