# Generated by Django 5.0.4 on 2024-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin_code',
            field=models.IntegerField(default=0),
        ),
    ]
