# Generated by Django 5.0.4 on 2024-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_profile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_account',
            field=models.IntegerField(default='83652146957175'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_account',
            field=models.IntegerField(default='547114994340'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
