# Generated by Django 5.0.4 on 2024-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_profile_bank_alter_profile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_account',
            field=models.IntegerField(default='33405688564321'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_account',
            field=models.IntegerField(default='167125008469'),
        ),
    ]
